// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/models/shared"
	"net/http"
)

type GetFinancialSettingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Given when resource was successfully returned.
	FinancialSettingsDto *shared.FinancialSettingsDto
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetFinancialSettingsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFinancialSettingsResponse) GetFinancialSettingsDto() *shared.FinancialSettingsDto {
	if o == nil {
		return nil
	}
	return o.FinancialSettingsDto
}

func (o *GetFinancialSettingsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFinancialSettingsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
