// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/utils"
	"net/http"
	"time"
)

type GetGeneralLedgerAccountsRequest struct {
	// Filter by account numbers. Separate by comma [,] to filter on multiple account numbers. A range of numbers can be specified using dash/hyphen [-]. For example "1000-1999, 2500, 3000-" will result in accounts with account numbers from and including 1000 to 1999, 2500, 3000 and all above will be returned. If null or whitespace, the filter is not used.
	AccountNos *string `queryParam:"style=form,explode=true,name=accountNos"`
	// Filter by agriculture departments. Separate by comma [,] to filter on multiple agriculture departments.
	AgricultureDepartments *string `queryParam:"style=form,explode=true,name=agricultureDepartments"`
	// Filter by last changed timestamp.
	LastChangedDateTimeOffsetGreaterThan *time.Time `queryParam:"style=form,explode=true,name=lastChangedDateTimeOffsetGreaterThan"`
	// Structure containing various resource-filter options
	ResourceParameter *shared.ResourceParameters `queryParam:"style=form,explode=true,name=resourceParameter"`
}

func (g GetGeneralLedgerAccountsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetGeneralLedgerAccountsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetGeneralLedgerAccountsRequest) GetAccountNos() *string {
	if o == nil {
		return nil
	}
	return o.AccountNos
}

func (o *GetGeneralLedgerAccountsRequest) GetAgricultureDepartments() *string {
	if o == nil {
		return nil
	}
	return o.AgricultureDepartments
}

func (o *GetGeneralLedgerAccountsRequest) GetLastChangedDateTimeOffsetGreaterThan() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastChangedDateTimeOffsetGreaterThan
}

func (o *GetGeneralLedgerAccountsRequest) GetResourceParameter() *shared.ResourceParameters {
	if o == nil {
		return nil
	}
	return o.ResourceParameter
}

type GetGeneralLedgerAccountsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Given when resource returned successfully
	Classes []shared.GeneralLedgerAccountDto
}

func (o *GetGeneralLedgerAccountsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGeneralLedgerAccountsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGeneralLedgerAccountsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetGeneralLedgerAccountsResponse) GetClasses() []shared.GeneralLedgerAccountDto {
	if o == nil {
		return nil
	}
	return o.Classes
}
