// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/models/shared"
	"net/http"
)

type GetSubLedgerNumberSeriesRequest struct {
	// Gets the underlying general ledger account code of this subledger series. Subledger transactions in Go will be posted using the subledger number, but the overall accounting effect will be on this underlying account. More information of accounts can be retrieved using the GeneralLedgerAccount service.
	GeneralLedgerAccountNos *string `queryParam:"style=form,explode=true,name=generalLedgerAccountNos"`
	// Filter series based on the isDefault property. Blank means no filter.
	IsDefault *bool `queryParam:"style=form,explode=true,name=isDefault"`
	// Structure containing various resource-filter options
	ResourceParameter *shared.ResourceParameters `queryParam:"style=form,explode=true,name=resourceParameter"`
	// Filter by SubledgerNumberSeriesType
	//             <br>Note: The SubLedgerNumberSeriesType filter is case sensitive.
	SubLedgerNumberSeriesType *string `queryParam:"style=form,explode=true,name=subLedgerNumberSeriesType"`
}

func (o *GetSubLedgerNumberSeriesRequest) GetGeneralLedgerAccountNos() *string {
	if o == nil {
		return nil
	}
	return o.GeneralLedgerAccountNos
}

func (o *GetSubLedgerNumberSeriesRequest) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *GetSubLedgerNumberSeriesRequest) GetResourceParameter() *shared.ResourceParameters {
	if o == nil {
		return nil
	}
	return o.ResourceParameter
}

func (o *GetSubLedgerNumberSeriesRequest) GetSubLedgerNumberSeriesType() *string {
	if o == nil {
		return nil
	}
	return o.SubLedgerNumberSeriesType
}

type GetSubLedgerNumberSeriesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Given when resource returned successfully
	Classes []shared.SubLedgerNumberSeriesDto
}

func (o *GetSubLedgerNumberSeriesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSubLedgerNumberSeriesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSubLedgerNumberSeriesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSubLedgerNumberSeriesResponse) GetClasses() []shared.SubLedgerNumberSeriesDto {
	if o == nil {
		return nil
	}
	return o.Classes
}
