// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/models/shared"
	"net/http"
)

type PatchGeneralLedgerAccountsIDRequest struct {
	// JSON Patch structure for updating a General Ledger Account. See GeneralLedgerAccountPatchDto schema for all available properties. For more information on JSON patch and the various operations allowed, check out: https://datatracker.ietf.org/doc/html/rfc6902
	RequestBody []shared.Operation `request:"mediaType=application/json-patch+json"`
	// The id of the general ledger account.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PatchGeneralLedgerAccountsIDRequest) GetRequestBody() []shared.Operation {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PatchGeneralLedgerAccountsIDRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type PatchGeneralLedgerAccountsIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Given when resource was successfully updated
	GeneralLedgerAccountDto *shared.GeneralLedgerAccountDto
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchGeneralLedgerAccountsIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchGeneralLedgerAccountsIDResponse) GetGeneralLedgerAccountDto() *shared.GeneralLedgerAccountDto {
	if o == nil {
		return nil
	}
	return o.GeneralLedgerAccountDto
}

func (o *PatchGeneralLedgerAccountsIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchGeneralLedgerAccountsIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
