// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/models/shared"
	"net/http"
)

type PostGeneralLedgerAccountsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Given when resource was successfully created
	GeneralLedgerAccountDto *shared.GeneralLedgerAccountDto
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostGeneralLedgerAccountsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostGeneralLedgerAccountsResponse) GetGeneralLedgerAccountDto() *shared.GeneralLedgerAccountDto {
	if o == nil {
		return nil
	}
	return o.GeneralLedgerAccountDto
}

func (o *PostGeneralLedgerAccountsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostGeneralLedgerAccountsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
