// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CurrencyDto - The currencies active for GUI operations.
type CurrencyDto struct {
	// Currency code.
	Code *string `json:"Code,omitempty"`
	// Value indication if this currency is active for this client.
	IsActive *bool `json:"IsActive,omitempty"`
	// English notation of the currency name.
	Notation *string `json:"Notation,omitempty"`
}

func (o *CurrencyDto) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *CurrencyDto) GetIsActive() *bool {
	if o == nil {
		return nil
	}
	return o.IsActive
}

func (o *CurrencyDto) GetNotation() *string {
	if o == nil {
		return nil
	}
	return o.Notation
}
