// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GeneralLedgerAccountPostDto - The General Ledger Account Post DTO contains only properties relevant to a general ledger account in Go that can be altered directly via POST-method in API.
type GeneralLedgerAccountPostDto struct {
	// The number of the account.
	AccountNo int64 `json:"AccountNo"`
	// The standard code of the currency associated with the account.
	CurrencyCode *string `json:"CurrencyCode,omitempty"`
	// The code of the department associated with the account.
	DepartmentCode *string `json:"DepartmentCode,omitempty"`
	// The id of the department associated with the account.
	DepartmentID *int64 `json:"DepartmentId,omitempty"`
	// Value indicating whether this account is active.
	// Accounts that are not active will not be available for users in the journal entry GUI.
	IsActive bool `json:"IsActive"`
	// Value indicating whether department is a required property to set on transactions on this account.
	IsDepartmentRequired *bool `json:"IsDepartmentRequired,omitempty"`
	// Value indicating whether project is a required property to set on transactions on this account.
	IsProjectRequired *bool `json:"IsProjectRequired,omitempty"`
	// Value indicating whether the account is locked to a VAT code. If true, only VatCode can be used on transactions on this account.
	IsVatCodeLocked *bool `json:"IsVatCodeLocked,omitempty"`
	// The name of the account.
	Name string `json:"Name"`
	// The VAT code associated with the account.
	// Standard codes in Go is based on the SAF-T standard.
	// Codes and any custom codes can be queried and identified using the VatCode service.
	VatCode string `json:"VatCode"`
	// Vat return specification used for giving extra vat information about the transaction. Will be reported from 2022 in the norwegian vat return.<p>Members:</p><ul><li><i>None</i> - None</li><li><i>Adjustment</i> - Adjustments (Norwegian: Justering)</li><li><i>LossesOnClaims</i> - Losses on claims (Norwegian: Tap på krav)</li><li><i>ReversalOfInputValueAddedTax</i> - Reversal of input value added tax (Norwegian: Tilbakeføring av inngående merverdiavgift)</li><li><i>Withdrawals</i> - Withdrawals (Norwegian: Uttak)</li><li><i>AdjustmentVatCompensationRealProperty</i> - Adjustment of value added tax (VAT) compensation for real estate (Norwegian: Justering av merverdiavgiftskompensasjon for fast eiendom)</li><li><i>PurchasesEligibleForCompensation</i> - Purchases eligible for compensation (Norwegian: Kjøp med kompensasjonsrett). This specification can not be used by the API directly when creating vouchers/account transactions, but will appear on account transactions on outgoing vat on purchases on client's eligible for compensation.</li></ul>
	VatReturnSpecification *VatReturnSpecification `json:"VatReturnSpecification,omitempty"`
}

func (o *GeneralLedgerAccountPostDto) GetAccountNo() int64 {
	if o == nil {
		return 0
	}
	return o.AccountNo
}

func (o *GeneralLedgerAccountPostDto) GetCurrencyCode() *string {
	if o == nil {
		return nil
	}
	return o.CurrencyCode
}

func (o *GeneralLedgerAccountPostDto) GetDepartmentCode() *string {
	if o == nil {
		return nil
	}
	return o.DepartmentCode
}

func (o *GeneralLedgerAccountPostDto) GetDepartmentID() *int64 {
	if o == nil {
		return nil
	}
	return o.DepartmentID
}

func (o *GeneralLedgerAccountPostDto) GetIsActive() bool {
	if o == nil {
		return false
	}
	return o.IsActive
}

func (o *GeneralLedgerAccountPostDto) GetIsDepartmentRequired() *bool {
	if o == nil {
		return nil
	}
	return o.IsDepartmentRequired
}

func (o *GeneralLedgerAccountPostDto) GetIsProjectRequired() *bool {
	if o == nil {
		return nil
	}
	return o.IsProjectRequired
}

func (o *GeneralLedgerAccountPostDto) GetIsVatCodeLocked() *bool {
	if o == nil {
		return nil
	}
	return o.IsVatCodeLocked
}

func (o *GeneralLedgerAccountPostDto) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GeneralLedgerAccountPostDto) GetVatCode() string {
	if o == nil {
		return ""
	}
	return o.VatCode
}

func (o *GeneralLedgerAccountPostDto) GetVatReturnSpecification() *VatReturnSpecification {
	if o == nil {
		return nil
	}
	return o.VatReturnSpecification
}
