// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/types"
	"github.com/speakeasy-sdks/MyCompany-sample-sdk/pkg/utils"
)

// LockDateSettingsDto - Represents the lock date settings of a client.
type LockDateSettingsDto struct {
	// Gets the lock date on the client. It's not possible to create accounting entries on this date or any previous date on this client.
	LockDate *types.Date `json:"LockDate,omitempty"`
}

func (l LockDateSettingsDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LockDateSettingsDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *LockDateSettingsDto) GetLockDate() *types.Date {
	if o == nil {
		return nil
	}
	return o.LockDate
}
