// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OperationValue struct {
}

type Operation struct {
	From  *string         `json:"from,omitempty"`
	Op    *string         `json:"op,omitempty"`
	Path  *string         `json:"path,omitempty"`
	Value *OperationValue `json:"value,omitempty"`
}

func (o *Operation) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *Operation) GetOp() *string {
	if o == nil {
		return nil
	}
	return o.Op
}

func (o *Operation) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *Operation) GetValue() *OperationValue {
	if o == nil {
		return nil
	}
	return o.Value
}
