// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResourceParametersInput - Structure containing various resource-filter options
type ResourceParametersInput struct {
	// Define desired fields that should be returned in Json (All fields by default).
	Fields *string `queryParam:"name=Fields"`
	// Define fields to order by, and if it should order asc (default) or desc).
	OrderBy *string `queryParam:"name=OrderBy"`
	// The desired page to return.
	PageNumber *int `queryParam:"name=PageNumber"`
	// The amount of objects to return in a Page (5000 by default). Not allowed to be larger than MaxPageSize.
	PageSize *int `queryParam:"name=PageSize"`
	// If set to true, all relevant filter-values will be validated against the database. NOTE: This will make the api-call much slower, but only for the initial request, as the validation-results are cached. Useful for debugging/support purposes.
	UseDatabaseValidation *bool `queryParam:"name=UseDatabaseValidation"`
}

func (o *ResourceParametersInput) GetFields() *string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *ResourceParametersInput) GetOrderBy() *string {
	if o == nil {
		return nil
	}
	return o.OrderBy
}

func (o *ResourceParametersInput) GetPageNumber() *int {
	if o == nil {
		return nil
	}
	return o.PageNumber
}

func (o *ResourceParametersInput) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ResourceParametersInput) GetUseDatabaseValidation() *bool {
	if o == nil {
		return nil
	}
	return o.UseDatabaseValidation
}
