// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Enum SubLedgerNumberSeriesType indicating what kind of sub ledger accounts are represented in the number series.<p>Members:</p><ul><li><i>Customer</i> - The sub ledger number series contains Customer</li><li><i>Supplier</i> - The sub ledger number series contains Supplier</li><li><i>Employee</i> - The sub ledger number series contains Employee</li></ul>
type SubLedgerNumberSeriesType string

const (
	SubLedgerNumberSeriesTypeCustomer SubLedgerNumberSeriesType = "Customer"
	SubLedgerNumberSeriesTypeSupplier SubLedgerNumberSeriesType = "Supplier"
	SubLedgerNumberSeriesTypeEmployee SubLedgerNumberSeriesType = "Employee"
)

func (e SubLedgerNumberSeriesType) ToPointer() *SubLedgerNumberSeriesType {
	return &e
}

func (e *SubLedgerNumberSeriesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Customer":
		fallthrough
	case "Supplier":
		fallthrough
	case "Employee":
		*e = SubLedgerNumberSeriesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SubLedgerNumberSeriesType: %v", v)
	}
}
