// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VatPeriodType - Enum defining the Value Added Tax (VAT) period on this client. The VAT period states how often VAT is reported to the government from this client.<p>Members:</p><ul><li><i>Weekly</i> - Every week</li><li><i>HalfMonthly</i> - Half-Monthly</li><li><i>Monthly</i> - Every month</li><li><i>BiMonthly</i> - Every two months</li><li><i>Yearly</i> - Once a year</li><li><i>HalfYearly</i> - Twice a year</li><li><i>Quarterly</i> - Four times a year</li></ul>
type VatPeriodType string

const (
	VatPeriodTypeWeekly      VatPeriodType = "Weekly"
	VatPeriodTypeHalfMonthly VatPeriodType = "HalfMonthly"
	VatPeriodTypeMonthly     VatPeriodType = "Monthly"
	VatPeriodTypeBiMonthly   VatPeriodType = "BiMonthly"
	VatPeriodTypeYearly      VatPeriodType = "Yearly"
	VatPeriodTypeHalfYearly  VatPeriodType = "HalfYearly"
	VatPeriodTypeQuarterly   VatPeriodType = "Quarterly"
)

func (e VatPeriodType) ToPointer() *VatPeriodType {
	return &e
}

func (e *VatPeriodType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Weekly":
		fallthrough
	case "HalfMonthly":
		fallthrough
	case "Monthly":
		fallthrough
	case "BiMonthly":
		fallthrough
	case "Yearly":
		fallthrough
	case "HalfYearly":
		fallthrough
	case "Quarterly":
		*e = VatPeriodType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VatPeriodType: %v", v)
	}
}
