// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VatReturnType - Maps to VatReturnCategory<p>Members:</p><ul><li><i>generalIndustry</i> - Alminnelig næring</li><li><i>primaryIndustry</i> - Primærnmæring</li><li><i>vatFeeCompensation</i> - Merverdiavgiftskompensasjon</li><li><i>reverseVatObligation</i> - Omvendt avgiftsplikt</li><li><i>noReporting</i> - Ingen rapportering</li></ul>
type VatReturnType string

const (
	VatReturnTypeGeneralIndustry      VatReturnType = "generalIndustry"
	VatReturnTypePrimaryIndustry      VatReturnType = "primaryIndustry"
	VatReturnTypeVatFeeCompensation   VatReturnType = "vatFeeCompensation"
	VatReturnTypeReverseVatObligation VatReturnType = "reverseVatObligation"
	VatReturnTypeNoReporting          VatReturnType = "noReporting"
)

func (e VatReturnType) ToPointer() *VatReturnType {
	return &e
}

func (e *VatReturnType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "generalIndustry":
		fallthrough
	case "primaryIndustry":
		fallthrough
	case "vatFeeCompensation":
		fallthrough
	case "reverseVatObligation":
		fallthrough
	case "noReporting":
		*e = VatReturnType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VatReturnType: %v", v)
	}
}
