// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VatReturnType - The type of VAT returns the client should deliver for it's principal activity.<p>Members:</p><ul><li><i>GeneralIndustry</i> - General Industry (Norwegian: Alminnelig næring)</li><li><i>PrimaryIndustry</i> - Primary Industry (Norwegian: Primærnmæring)</li><li><i>VatCompensation</i> - Vat Compensation (Norwegian: Merverdiavgiftskompensasjon)ø</li><li><i>ReverseVatLiability</i> - Reverse VAT Liability (Norwegian: Omvendt avgiftsplikt)</li><li><i>NoReporting</i> - No reporting (Norwegian: Ingen rapportering)</li></ul>
type VatReturnType string

const (
	VatReturnTypeGeneralIndustry     VatReturnType = "GeneralIndustry"
	VatReturnTypePrimaryIndustry     VatReturnType = "PrimaryIndustry"
	VatReturnTypeVatCompensation     VatReturnType = "VatCompensation"
	VatReturnTypeReverseVatLiability VatReturnType = "ReverseVatLiability"
	VatReturnTypeNoReporting         VatReturnType = "NoReporting"
)

func (e VatReturnType) ToPointer() *VatReturnType {
	return &e
}

func (e *VatReturnType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GeneralIndustry":
		fallthrough
	case "PrimaryIndustry":
		fallthrough
	case "VatCompensation":
		fallthrough
	case "ReverseVatLiability":
		fallthrough
	case "NoReporting":
		*e = VatReturnType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VatReturnType: %v", v)
	}
}
