// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VatReturnSpecification - Vat return specification used for giving extra vat information about the transaction. Will be reported from 2022 in the norwegian vat return.<p>Members:</p><ul><li><i>none</i> - None</li><li><i>adjustment</i> - Adjustments (Norwegian: Justering)</li><li><i>lossesOnClaims</i> - Losses on claims (Norwegian: Tap på krav)</li><li><i>reversalOfInputValueAddedTax</i> - Reversal of input value added tax (VAT) (Norwegian: Tilbakeføring av inngående merverdiavgift)</li><li><i>withdrawals</i> - Withdrawals (Norwegian: Uttak)</li><li><i>adjustmentVatCompensationRealProperty</i> - Adjustment of value added tax (VAT) compensation for real estate (Norwegian: Justering av merverdiavgiftskompensasjon for fast eiendom)</li><li><i>purchasesEligibleForCompensation</i> - Purchases eligible for compensation (Norwegian: Kjøp med kompensasjonsrett)</li></ul>
type VatReturnSpecification string

const (
	VatReturnSpecificationNone                                  VatReturnSpecification = "none"
	VatReturnSpecificationAdjustment                            VatReturnSpecification = "adjustment"
	VatReturnSpecificationLossesOnClaims                        VatReturnSpecification = "lossesOnClaims"
	VatReturnSpecificationReversalOfInputValueAddedTax          VatReturnSpecification = "reversalOfInputValueAddedTax"
	VatReturnSpecificationWithdrawals                           VatReturnSpecification = "withdrawals"
	VatReturnSpecificationAdjustmentVatCompensationRealProperty VatReturnSpecification = "adjustmentVatCompensationRealProperty"
	VatReturnSpecificationPurchasesEligibleForCompensation      VatReturnSpecification = "purchasesEligibleForCompensation"
)

func (e VatReturnSpecification) ToPointer() *VatReturnSpecification {
	return &e
}

func (e *VatReturnSpecification) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "adjustment":
		fallthrough
	case "lossesOnClaims":
		fallthrough
	case "reversalOfInputValueAddedTax":
		fallthrough
	case "withdrawals":
		fallthrough
	case "adjustmentVatCompensationRealProperty":
		fallthrough
	case "purchasesEligibleForCompensation":
		*e = VatReturnSpecification(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VatReturnSpecification: %v", v)
	}
}
